const data = [
  {
    id: 1,
    title: "Beef Shake Love",
    image: "https://www.themealdb.com/images/category/beef.png",
    category: "shake",
    price: 12.9,
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus quod ea facere cupiditate quaerat minus labore inventore, ab vitae omnis!",
  },
  {
    id: 2,
    title: "Desert Shake Love",
    image: "https://www.themealdb.com/images/category/dessert.png",
    category: "shake",
    price: 34.09,
    info: "tate quaerat minus labore inventore, ab vitae omnis!quaerat minus labore inventore, ab vitae omnis",
  },
  {
    id: 3,
    title: "Miscellaneous Shake Love",
    image: "https://www.themealdb.com/images/category/miscellaneous.png",
    category: "shake",
    price: 66.54,
    info: "letur adipisicing elit. Doloribus quod ea facere cupiditate quaerat minus labore inventore, ab vitae omnis!quaerat minus labore inventore.",
  },
  {
    id: 4,
    title: "Pasta Lunch Love",
    image: "https://www.themealdb.com/images/category/pasta.png",
    category: "lunch",
    price: 99.09,
    info: " quaerat minus labore inventore, ab vitae omnis! quaerat minus labore inventore, ab vitae omnisquaerat minus labore inventore, ab vitae omnis",
  },
  {
    id: 5,
    title: "Pork Lunch Love",
    image: "https://www.themealdb.com/images/category/pork.png",
    category: "lunch",
    price: 22.09,
    info: "quaerat minus labore inventore, ab vitae omnisquaerat minus labore inventore, ab vitae omnis",
  },
  {
    id: 6,
    title: "Side Lunch Love",
    image: "https://www.themealdb.com/images/category/side.png",
    category: "lunch",
    price: 77.02,
    info: "quaerat minus labore inventore, ab vitae omnisquaerat minus labore inventore, ab vitae omnis",
  },
  {
    id: 7,
    title: "Starter Breakfast Love",
    image: "https://www.themealdb.com/images/category/starter.png",
    category: "breakfast",
    price: 78.2,
    info: "quaerat minus labore inventore, ab vitae omnisquaerat minus labore inventore, ab vitae omnis",
  },
  {
    id: 8,
    title: "Vegan Breakfast Love",
    image: "https://www.themealdb.com/images/category/vegan.png",
    category: "breakfast",
    price: 99.99,
    info: "quaerat minus labore inventore, ab vitae omnisquaerat minus labore inventore, ab vitae omnis",
  },
  {
    id: 9,
    title: "Cheese Breakfast Love",
    image: "https://www.themealdb.com/images/category/breakfast.png",
    category: "breakfast",
    price: 12.65,
    info: "quaerat minus labore inventore, ab vitae omnisquaerat minus labore inventore, ab vitae omnis",
  },
];

export default data;
